import { t } from "../lib/i18n";
import { SRC } from "./sources";
import type { RefEntry } from "./types";

export const REFERENCE: RefEntry[] = [
  { id: "pattern-select", term: "[PATTERN SELECT]", category: "controls", status: "verified", answer: t("Вход в паттерн-секвенсор: отсюда создают и выбирают паттерны.", "Enters the pattern sequencer: patterns are created and selected from here."), see: { area: "trick", id: "tr-rec" }, sources: [SRC.trrec] },
  { id: "rec", term: "[REC]", category: "controls", status: "verified", answer: t("Начинает запись: в TR-REC — запись паттерна, в skip-back — сохранение захваченного звука на пэд.", "Starts recording: in TR-REC it records the pattern, in skip-back it saves the captured sound to a pad."), sources: [SRC.trrec, SRC.skipback] },
  { id: "remain", term: "[REMAIN]", category: "controls", status: "verified", answer: t("В режиме записи паттерна переключает способ записи на «TR-REC»; в редакторе цепочки паттернов переключает повтор (All / Current / Off).", "In pattern recording it switches the recording method to “TR-REC”; in the pattern chain editor it switches repeat (All / Current / Off)."), sources: [SRC.trrec, SRC.chain] },
  { id: "sub-pad", term: "[SUB PAD]", category: "controls", status: "verified", answer: t("Удерживая её в TR-REC, выбираешь пэд с сэмплом; в цепочке паттернов запускает и останавливает воспроизведение.", "Held in TR-REC, you choose the pad with the sample; in a pattern chain it starts and stops playback."), sources: [SRC.trrec, SRC.chain] },
  { id: "exit", term: "[EXIT]", category: "controls", status: "verified", answer: t("Завершает действие и возвращает к предыдущему экрану: в MUTE GROUP сохраняет настройки, в TR-REC два нажатия сохраняют паттерн. В skip-back без назначения на пэд память теряется.", "Finishes the action and returns to the previous screen: in MUTE GROUP it saves the settings, in TR-REC two presses save the pattern. In skip-back, the memory is lost if it isn't assigned to a pad."), sources: [SRC.mute, SRC.skipback] },
  { id: "mark", term: "[MARK]", category: "controls", status: "verified", answer: t("В skip-back показывает волну захваченного звука; мигает, когда звук записывается в skip-back память.", "In skip-back it shows the waveform of the captured sound; it blinks while sound is being recorded into skip-back memory."), see: { area: "trick", id: "skip-back" }, sources: [SRC.skipback] },
  { id: "shift", term: "[SHIFT]", category: "controls", status: "verified", answer: t("Модификатор: вместе с пэдами открывает экраны и функции (например, [SHIFT] + пэд [8] — MUTE GROUP).", "Modifier: together with pads it opens screens and functions (for example [SHIFT] + pad [8] — MUTE GROUP)."), sources: [SRC.mute] },
  { id: "hold", term: "[HOLD]", category: "controls", status: "verified", answer: t("Удерживая её и нажимая пэды [1]–[16], выбирают номер цепочки паттернов.", "Hold it and press pads [1]–[16] to choose the pattern chain number."), see: { area: "trick", id: "pattern-chain" }, sources: [SRC.chain] },
  { id: "value", term: "[VALUE]", category: "controls", status: "verified", answer: t("Ручка выбора значений (например, группа A–J в MUTE GROUP). Если удерживать её и крутить ручки CTRL, открываются дополнительные параметры эффекта.", "The value knob (for example the group A–J in MUTE GROUP). Hold it and turn the CTRL knobs to open extra effect parameters."), sources: [SRC.mute, SRC.bus] },
  { id: "ctrl", term: "[CTRL 1]–[CTRL 3]", category: "controls", status: "verified", answer: t("Ручки, которыми меняют параметры включённого эффекта; какая за что — видно на дисплее.", "The knobs that change the parameters of the active effect; the display shows which does what."), sources: [SRC.bus] },
  { id: "fx-buttons", term: t("Кнопки эффектов", "Effect buttons"), category: "controls", status: "verified", answer: t("[FILTER+DRIVE], [RESONATOR], [DELAY], [ISOLATOR], [DJFX LOOPER], [MFX] включают эффект; их назначение можно менять (DIRECT FX).", "[FILTER+DRIVE], [RESONATOR], [DELAY], [ISOLATOR], [DJFX LOOPER], [MFX] turn an effect on; their assignment can be changed (DIRECT FX)."), sources: [SRC.bus] },
  { id: "resample", term: "[RESAMPLE]", category: "controls", status: "verified", answer: t("Сэмплирование паттерна в новый сэмпл на пэд.", "Sampling a pattern into a new sample on a pad."), see: { area: "trick", id: "resample-pattern" }, sources: [SRC.resample] },
  { id: "del", term: "[DEL]", category: "controls", status: "verified", answer: t("В редакторе цепочки паттернов удаляет паттерн под курсором; [SHIFT] + [DEL] отменяет правки.", "In the pattern chain editor it deletes the pattern under the cursor; [SHIFT] + [DEL] undoes edits."), sources: [SRC.chain] },
  { id: "skipback-mem", term: t("Skip-back память", "Skip-back memory"), category: "concepts", status: "verified", answer: t("Хранит последние до 25 секунд звука (до 40 при Mark Function = «SBS Long»). Теряется, если не назначить на пэд до [EXIT] или выключения.", "Keeps up to the last 25 seconds of sound (up to 40 with Mark Function = “SBS Long”). It is lost if not assigned to a pad before [EXIT] or power-off."), see: { area: "trick", id: "skip-back" }, sources: [SRC.skipback] },
  { id: "mute-group-def", term: "Mute Group", category: "concepts", status: "verified", answer: t("До 10 групп (A–J) по 16 сэмплов; в группе звучит только последний сыгранный пэд.", "Up to 10 groups (A–J) of 16 samples; in a group only the last played pad sounds."), see: { area: "trick", id: "mute-group" }, sources: [SRC.mute] },
  { id: "pad-colors", term: t("Цвет мигающих пэдов", "Colour of blinking pads"), category: "concepts", status: "verified", answer: t("При записи паттерна пустые пэды мигают красным, а пэды с уже записанным паттерном — синим.", "When recording a pattern, empty pads blink red and pads with a recorded pattern blink blue."), sources: [SRC.resample, SRC.trrec] },
  { id: "tr-rec-def", term: "TR-REC", category: "workflow", status: "verified", answer: t("Способ записи паттерна по шагам: пэды [1]–[16] — это шаги, сэмпл выбирается удержанием [SUB PAD].", "A step-by-step pattern recording method: pads [1]–[16] are the steps, the sample is chosen by holding [SUB PAD]."), see: { area: "trick", id: "tr-rec" }, sources: [SRC.trrec] },
  { id: "chain-def", term: t("Цепочка паттернов", "Pattern chain"), category: "workflow", status: "verified", answer: t("Порядок паттернов, который играет сам; номер цепочки выбирают удерживая [HOLD] и нажимая пэд.", "An order of patterns that plays by itself; the chain number is chosen by holding [HOLD] and pressing a pad."), see: { area: "trick", id: "pattern-chain" }, sources: [SRC.chain] },
  { id: "sc-mute", term: t("[SHIFT] + пэд [8]", "[SHIFT] + pad [8]"), category: "shortcuts", status: "verified", answer: t("Открывает экран MUTE GROUP.", "Opens the MUTE GROUP screen."), see: { area: "trick", id: "mute-group" }, sources: [SRC.mute] },
  { id: "sc-click", term: t("[SHIFT] + пэд [9]", "[SHIFT] + pad [9]"), category: "shortcuts", status: "verified", answer: t("Включает и выключает метроном (параметр SYSTEM «CLICK»).", "Turns the metronome on and off (SYSTEM parameter “CLICK”)."), sources: [SRC.resample] },
  { id: "fx-djfx", term: "DJFX Looper", category: "effects", status: "verified", answer: t("Зацикливает звук короткими циклами, меняет направление и скорость (LENGTH, SPEED, LOOP SW).", "Loops the sound in short cycles, changes direction and speed (LENGTH, SPEED, LOOP SW)."), see: { area: "fx", id: "djfx-looper" }, sources: [SRC.djfx] },
  { id: "fx-filter", term: "Filter+Drive", category: "effects", status: "verified", answer: t("Фильтр с овердрайвом: CUTOFF, RESONANCE, DRIVE, FLT TYPE, LOW FREQ, LOW GAIN.", "A filter with overdrive: CUTOFF, RESONANCE, DRIVE, FLT TYPE, LOW FREQ, LOW GAIN."), see: { area: "fx", id: "filter-drive" }, sources: [SRC.filter] },
  { id: "fx-resonator", term: "Resonator", category: "effects", status: "verified", answer: t("Резонаторы на нотах или аккорде: ROOT, BRIGHT, FEEDBACK, CHORD, PANNING, ENV MOD.", "Resonators on notes or a chord: ROOT, BRIGHT, FEEDBACK, CHORD, PANNING, ENV MOD."), see: { area: "fx", id: "resonator" }, sources: [SRC.resonator] },
  { id: "fx-isolator", term: "Isolator", category: "effects", status: "verified", answer: t("Раздельная регулировка низа, середины и верха (LOW, MID, HIGH).", "Separate control of lows, mids and highs (LOW, MID, HIGH)."), see: { area: "fx", id: "isolator" }, sources: [SRC.isolator] },
];

export const CATEGORY_LABELS: Record<string, string> = { controls: t("Кнопки и ручки", "Buttons and knobs"), concepts: t("Понятия", "Concepts"), shortcuts: t("Сочетания", "Combos"), effects: t("Эффекты", "Effects"), workflow: t("Рабочий процесс", "Workflow") };

/** Plain filter: matches term and answer, case-insensitive, optional category. */
export function searchReference(entries: RefEntry[], query: string, category?: string | null): RefEntry[] {
  const q = query.trim().toLowerCase();
  return entries.filter((e) => e.status === "verified" && (!category || e.category === category)
    && (!q || e.term.toLowerCase().includes(q) || e.answer.toLowerCase().includes(q)));
}
